name: nix-macos

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v7
    - name: Setup repo
      run: |
        git submodule init && git submodule update
    - uses: cachix/cachix-action@v4
      with:
        name: hasktorch
        skipNixBuild: false
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
