name: nix-jupyterlab

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v7
    - name: Setup repo
      run: |
        git submodule init && git submodule update
    - uses: cachix/cachix-action@v4
      with:
        name: hasktorch
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        skipNixBuild: false
        file: experimental/jupyterlab/default.nix
        nixBuildArgs: --option sandbox false 
#    - name: Build
#      run: |
#        nix-env -i cachix
#        cachix use hasktorch
#        cachix use jupyterwith
#        cd experimental/jupyterlab
#        nix-shell --option sandbox false --command "echo"
